#ifndef PROJECT_CONFIG_H
#define PROJECT_CONFIG_H

#define PROJECT_NAME "example-interactions"
#define PROJECT_VERSION "1.0.0"
#define PROJECT_VERSION_MAJOR "1"
#define PROJECT_VERSION_MINOR "0"
#define PROJECT_VERSION_PATCH "0"

#endif // PROJECT_CONFIG_H
